name: Build and Push Docker Image Manually

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract Git tag
        id: git_tag
        run: echo "::set-output name=TAG::$(git describe --tags --abbrev=0)"

      - name: Remove 'release/' prefix from tag
        id: version
        run: |
          TAG=${{ steps.git_tag.outputs.TAG }}
          VERSION=${TAG#release/}
          echo "::set-output name=VERSION::$VERSION"

      - name: Extract repository name
        id: repo_name
        run: echo "::set-output name=NAME::$(basename ${{ github.repository }})"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.repo_name.outputs.NAME }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.repo_name.outputs.NAME }}:${{ steps.version.outputs.VERSION }}
          file: ./release.Dockerfile

      - name: Logout from Docker Hub
        run: docker logout
